name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: foxy
          ROS_REPO: main
          ADDITIONAL_DEBS: "tree"
          BEFORE_RUN_TARGET_TEST: "tree -L 2 /root/target_ws/build/"